# Generated by Django 6.0 on 2026-01-04 11:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('frais_livraison', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ParametresRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_restaurant', models.CharField(default='Le Cube', max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('paiement_airtel_active', models.BooleanField(default=True)),
                ('paiement_mobilecash_active', models.BooleanField(default=True)),
                ('paiement_livraison_active', models.BooleanField(default=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0.18, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Paramètres du Restaurant',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Ex: orders.preparation.update', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('MENU', 'Menu'), ('BASE', 'Base'), ('ACCOMPAGNEMENT', 'Accompagnement'), ('SUPPLEMENT', 'Supplément')], default='BASE', max_length=20)),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categorie', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EPUISE', 'Épuisé')], default='ACTIF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variations', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('statut_commande', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('EN_PREPARATION', 'En préparation'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_preparation', models.DateTimeField(blank=True, null=True)),
                ('date_depart_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_livree', models.DateTimeField(blank=True, null=True)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frais_livraison', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('livreur_position_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('livreur_position_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AIRTEL_MONEY', 'Airtel Money'), ('MOBILE_CASH', 'Mobile Cash'), ('LIVRAISON', 'Paiement à la livraison')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=500, null=True)),
                ('montant_en_especes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='core_api.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('reduction', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('id_variation', models.CharField(blank=True, max_length=50, null=True)),
                ('personnalisation', models.TextField(blank=True, null=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_api.panier')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.plat')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_variation', models.CharField(blank=True, max_length=50, null=True)),
                ('personnalisation', models.TextField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core_api.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_api.plat')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='core_api.permission')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.role'),
        ),
    ]
